[package]
name = "janus-video-room"
version = "0.1.0"
authors = ["Philippe Normand <philn@igalia.com>"]
edition = "2018"
license = "LGPL"

[dependencies]
futures = "0.3"
structopt = { version = "0.3", default-features = false }
anyhow = "1"
url = "2"
rand = "0.8"
async-tungstenite = { version = "0.17", features = ["gio-runtime"] }
gst = { package = "gstreamer", version = "0.18", features = ["v1_14"] }
gst-webrtc = { package = "gstreamer-webrtc", version = "0.18" }
gst-sdp = { package = "gstreamer-sdp", version = "0.18", features = ["v1_14"] }
serde = "1"
serde_derive = "1"
serde_json = "1.0.53"
http = "0.2"
glib = "0.15"
gio = "0.15"
log = "0.4.8"
env_logger = "0.9"
