[package]
name = "webrtc-app"
version = "0.1.0"
authors = ["Sebastian Dr√∂ge <sebastian@centricular.com>"]
edition = "2018"

[workspace]

[dependencies]
futures = "0.3"
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
rand = { version = "0.9", features = ["thread_rng"] }
async-tungstenite = { version = "0.30", features = ["tokio-runtime", "tokio-native-tls"] }
gst = { package = "gstreamer", version = "0.24" }
gst-webrtc = { package = "gstreamer-webrtc", version = "0.24" }
gst-sdp = { package = "gstreamer-sdp", version = "0.24" }
serde = "1"
serde_derive = "1"
serde_json = "1"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.26"
