[package]
name = "webrtc-app"
version = "0.1.0"
authors = ["Sebastian DrÃ¶ge <sebastian@centricular.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
async-std = "1"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
rand = "0.8"
async-tungstenite = { version = "0.23", features = ["async-std-runtime", "async-native-tls"] }
gst = { package = "gstreamer", version = "0.21" }
gst-webrtc = { package = "gstreamer-webrtc", version = "0.21" }
gst-sdp = { package = "gstreamer-sdp", version = "0.21" }
serde = "1"
serde_derive = "1"
serde_json = "1"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.25"
