[package]
name = "webrtc-app"
version = "0.1.0"
authors = ["Sebastian DrÃ¶ge <sebastian@centricular.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
async-std = "1"
structopt = { version = "0.3", default-features = false }
anyhow = "1"
rand = "0.7"
async-tungstenite = { version = "0.4", features = ["async-std-runtime", "async-native-tls"] }
gst = { package = "gstreamer", version = "0.15", features = ["v1_14"] }
gst-webrtc = { package = "gstreamer-webrtc", version = "0.15" }
gst-sdp = { package = "gstreamer-sdp", version = "0.15", features = ["v1_14"] }
serde = "1"
serde_derive = "1"
serde_json = "1"
